### ISSUE TITLE
`input_allocation` missing in `EVENT_NAMES`

### ISSUE THREAD

**Issue by RodolfoSaldivar** [underdog-tech/react-modal#29]
Official documentation states that the new `input_allocation` event is ready to use but the code does not has it in the list.

Documentation:
https://docs.pinwheelapi.com/docs/link-1#link-events
<img width="827" alt="image" src="https://user-images.githubusercontent.com/33875215/197809170-c7dc114e-d432-4d24-9cb1-1f0e7b2cebfd.png">

Code:
https://github.com/underdog-tech/react-modal/blob/master/src/index.tsx#L64
<img width="406" alt="image" src="https://user-images.githubusercontent.com/33875215/197809232-400f5d1e-d0f1-4172-8e71-f1d6ad35b770.png">

Can you please add it to the event names to fix the typescript error?
<img width="855" alt="image" src="https://user-images.githubusercontent.com/33875215/197809539-d4cf54fd-3ed2-4db4-94c9-721e517cd5c3.png">

**Comment by roscioli** [comment]
Thank you for the flag @RodolfoSaldivar !

**Comment by roscioli** [comment]
Fixed with https://github.com/underdog-tech/react-modal/pull/59
